apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster

resources:
  - https://raw.githubusercontent.com/stakater/Reloader/v1.4.12/deployments/kubernetes/reloader.yaml

patches:
  - path: reloader.yml
