apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system

resources:
  # Cloudflare Operator (latest stable)
  - https://github.com/adyanth/cloudflare-operator/config/default?ref=v0.13.1
  # Local resources
  - cloudflare-cred.yml
  - cluster-tunnel.yml
  - tunnel-bindings.yml
