apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.34.0/controller.yaml
  - backup.yml

patches:
  - path: resource.yaml
