apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-env
  namespace: monitoring
data:
  GF_SERVER_ROOT_URL: "https://grafana.ygnv.my.id/"
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.ygnv.my.id/application/o/authorize/"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.ygnv.my.id/application/o/token/"
  GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.ygnv.my.id/application/o/userinfo/"
  GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.ygnv.my.id/application/o/grafana/end-session/"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: reg.ygnv.my.id/docker/grafana/grafana:12.3.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: grafana-env
            - secretRef:
                name: grafana-cred
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-alerts
              mountPath: /etc/grafana/provisioning/alerting
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-alerts
          projected:
            sources:
              - configMap:
                  name: grafana-alerts-cpu
                  items:
                    - key: alerts-cpu.yaml
                      path: alerts-cpu.yaml
              - configMap:
                  name: grafana-alerts-ram
                  items:
                    - key: alerts-ram.yaml
                      path: alerts-ram.yaml
              - configMap:
                  name: grafana-alerts-reboot
                  items:
                    - key: alerts-reboot.yaml
                      path: alerts-reboot.yaml
              - configMap:
                  name: grafana-alerts-storage
                  items:
                    - key: alerts-storage.yaml
                      path: alerts-storage.yaml
              - configMap:
                  name: grafana-alerts-ceph
                  items:
                    - key: alerts-ceph.yaml
                      path: alerts-ceph.yaml
        - name: grafana-data

          hostPath:
            path: /mnt/cephfs/docker/monitoring/grafana
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`grafana.ygnv.my.id`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
  tls: {}
