apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/adyanth/cloudflare-operator/releases/download/v0.13.1/cloudflare-operator.crds.yaml
  - https://github.com/adyanth/cloudflare-operator/releases/download/v0.13.1/cloudflare-operator.yaml
  - cloudflare-cred.yml
  - cloudflare-tunnel.yml
