apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  # CRD from upstream
  - https://raw.githubusercontent.com/traefik/traefik/refs/tags/v3.6.5/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/refs/tags/v3.6.5/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  # Local resources
  - valkey.yml
  - config.yml
  - traefik.yml
  - service-account.yml
  - ingress.yml
  - tls-store.yml
  - certificate.yml
