apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  # CRD from upstream
  - https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  # Local resources
  - rbac.yml
  - valkey.yml
  - config.yml
  - traefik.yml
  - ingress.yml
  - tls-store.yml
  - certificate.yml
