---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - http
    - https
  routes:
    - match: Host(`reg.ygnv.my.id`)
      kind: Rule
      services:
        - name: harbor
          port: 80
  tls: {}
